MyReddit/config/routes.rb
Rails.application.routes.draw do

    resource :session, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show]
    resources :subs do 
        resources :posts, only: [:create]
    end 
    resources :posts, except: [:index, :create]

    
end

MyReddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyReddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  auth_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true 

  # belongs_to :sub,
  # foreign_key: :sub_id,
  # class_name: :Sub 

  belongs_to :author,
  foreign_key: :auth_id,
  class_name: :User 

  
  has_many :post_subs,
  foreign_key: :sub_id,
  class_name: :PostSub
  
  has_many :subs,
  through: :post_subs,
  source: :sub
end

MyReddit/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  belongs_to :sub, 
  foreign_key: :sub_id,
  class_name: :Sub 

  belongs_to :post, 
  foreign_key: :post_id,
  class_name: :Post

end

MyReddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true 

  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User 

  
  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub
  
  has_many :posts,
  through: :post_subs,
  source: :post
 
end

MyReddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true 
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :subs,
  foreign_key: :moderator_id,
  class_name: :Sub 

  has_many :posts,
  through: :subs,
  source: :posts

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def self.find_by_credentials(username, pw)
    user = User.find_by(username: username)
    if user && user.is_password?(pw)
      return user
    else 
      nil 
    end
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

end

MyReddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end 

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil 
  end

  

end

MyReddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  

  # def require_author
  #   redirect_to edit_post_url(@post) unless current_user.id == @post.auth_id
  # end

  
  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end


  def edit
    @post = Post.find(params[:id]) 
  end

 
  def create
    @post = Post.new(post_params)    
    @post.sub_id = params[:sub_id]     
    @post.auth_id = current_user.id

   if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit 
    end
  end

 
  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, [:sub_ids]) #array of sub ids
  end

end

MyReddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
      )
    if user
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Wrong User Credentials, Fucker']
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

MyReddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

 
  def index
    @subs = Sub.all
  end


  def show
    @sub = Sub.find(params[:id])
  end


  def new
    @sub = Sub.new
  end

  
  def edit
    @sub = Sub.find(params[:id])

  end

 
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end


  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find(params[:id])
    @sub.destroy!
    @sub.posts.each do |post|
      post.destroy!
    end 
    redirect_to subs_url
  end


  private

    
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

MyReddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new 
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

MyReddit/app/helpers/application_helper.rb
module ApplicationHelper
end

MyReddit/app/helpers/posts_helper.rb
module PostsHelper
end

MyReddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

MyReddit/app/helpers/subs_helper.rb
module SubsHelper
end

MyReddit/app/helpers/users_helper.rb
module UsersHelper
end

MyReddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capy-Reddit</title>
    <link rel="shortcut icon" href="https://us.123rf.com/450wm/robuart/robuart1708/robuart170800032/84986155-stock-vector-capybara-cartoon-icon-in-flat-design.jpg?ver=6" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <img src=https://us.123rf.com/450wm/robuart/robuart1708/robuart170800032/84986155-stock-vector-capybara-cartoon-icon-in-flat-design.jpg?ver=6' height='50px' width="50px"/>
      <% if logged_in? %>
        Welcome, <%= current_user.username %>!
        <form action="<%=session_url%>" method='post'>
          <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
          <input type="hidden" name='_method' value='delete' >
          <input type="submit" value='Logout!'></form>
      <% else %>
        How did you get here?
      <% end %>
    <%= yield %>
  </body>
</html>

MyReddit/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<form action="<%=post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="">
    Title
    <input type="text" name="post[title]" value='<%=@post.title%>'>
  </label>
  <br>
  <label for="">
    URL
    <input type="text" name="post[url]" value='<%=@post.url%>'>
  </label>
  <br>
  <label for="">
    Content
    <input type="text" name="post[content]" value='<%=@post.content%>'>
  </label>
  <br>
  <input type="submit" value="Submit!">

</form>

MyReddit/app/views/subs/_subpartial.html.erb
<h1> Something is working!!!!</h1>

MyReddit/app/views/subs/edit.html.erb
<h1>New Submission!</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type='hidden' name='_method' value='patch'>
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <p>Hello, <%=current_user.username%></p>
  <label for="">
  Title: 
    <input type="text" name="sub[title]" value='<%=@sub.title%>'>
  </label><br><br>
  <label for="">
  Description:<br>
   <textarea rows='5' columns='500' name='sub[description]'>
  <%=@sub.description%>
   </textarea>
  </label><br>

  <input type="submit" value="Submit!!!">

</form>

MyReddit/app/views/subs/index.html.erb
<h1>Subs, bitches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>

        <h3><%= sub.title %></h3><br>
        <%= link_to 'Show', sub %> <br>
        <%= link_to 'Edit', edit_sub_path(sub) %> <br>
        <%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %> <br>
    <h4>------------</h4>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

MyReddit/app/views/subs/new.html.erb
<h1>New Submission!</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="">
  Title: 
    <input type="text" name="sub[title]">
  </label><br><br>
  <label for="">
  Description:<br>
   <textarea rows='5' columns='50' name='sub[description]'>Sumthing?</textarea>
  </label><br>

  <input type="submit" value="Submit!!!">

</form>

MyReddit/app/views/subs/show.html.erb
<p>
  <i>Title:</i> <%=@sub.title%><br><br>
  <b>Description:</b><br><%=@sub.description%>
</p>
  <ul>
  <% @sub.posts.each do |post| %>
    <li><h3><%= post.title %></h3>
    <ul>  
    <i><%= post.url %></i><br>
    <%= post.content %></li> <br></ul>

    <a href='<%=edit_post_url(post)%>'><i>Edit Post</i></a><br>
  -------------------------

  <% end  %>
</ul>

<h2>Add Post</h2>
<form action="<%=sub_posts_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="">
    Title
    <input type="text" name="post[title]">
  </label>
  <br>
  <label for="">
    URL
    <input type="text" name="post[url]">
  </label>
  <br>
  <label for="">
    Content
    <input type="text" name="post[content]">
  </label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="<%=@sub.id%>">
  <input type="submit" value="Submit!">

</form>

MyReddit/app/views/users/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

MyReddit/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

MyReddit/app/views/users/new.html.erb
<h1>Sign Up Muthafucka!!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>%">

  <label for="">
  Username: 
    <input type="text" name="user[username]">
  </label>
  <label for="">
  Word of Passing:
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Submit!!!">

</form>

MyReddit/app/views/users/show.html.erb
<h1>Welcome!</h1>

<p>Hello there, <%= @user.username %>!
You owe me money, bitch! </p>